import { TNodeConfigurations } from "../model/types/node-config";

export const nodeConfigurations: TNodeConfigurations = {
    discreteInput: {
        dataType: "bool",
        type: "discreteInput",
        inputHandlesCount: 0,
        resultOffset: null,
        outputHandlesCount: 1,
        name: "",
    },
    discreteOutput: {
        dataType: "bool",
        type: "discreteOutput",
        inputHandlesCount: 0,
        resultOffset: null,
        outputHandlesCount: 1,
        name: "",
    },
    analogInput: {
        dataType: "float",
        type: "analogInput",
        inputHandlesCount: 0,
        setpointOffset: null,
        outputHandlesCount: 1,
        name: "",
    },
    analogOutput: {
        dataType: "float",
        type: "analogOutput",
        inputHandlesCount: 0,
        resultOffset: null,
        outputHandlesCount: 1,
        name: "",
    },
    xor: {
        dataType: "bool",
        type: "xor",
        inputHandlesCount: 2,
        resultOffset: null,
        outputHandlesCount: 1,
    },
    and: {
        dataType: "bool",
        type: "and",
        inputHandlesCount: 2,
        resultOffset: null,
        outputHandlesCount: 1,
    },
    or: {
        dataType: "bool",
        type: "or",
        inputHandlesCount: 3,
        resultOffset: null,
        outputHandlesCount: 1,
    },
    nand: {
        dataType: "bool",
        type: "nand",
        inputHandlesCount: 3,
        resultOffset: null,
        outputHandlesCount: 1,
    },
    nor: {
        dataType: "bool",
        type: "nor",
        inputHandlesCount: 3,
        resultOffset: null,
        outputHandlesCount: 1,
    },
    notOperation: {
        dataType: "bool",
        type: "notOperation",
        inputHandlesCount: 1,
        resultOffset: null,
        outputHandlesCount: 1,
    },
    sumInt: {
        dataType: "int",
        type: "sumInt",
        inputHandlesCount: 2,
        resultOffset: null,
        outputHandlesCount: 1,
    },
    // sumFloat: {
    //     dataType: "float",
    // type:,
    // inputHandlesCount: 2,
    //oresultOffset:null
    // utputHandlesCount: 1,
    //     width: 0,
    //     height: 0,
    // },
    multInt: {
        dataType: "int",
        type: "multInt",
        inputHandlesCount: 2,
        resultOffset: null,
        outputHandlesCount: 1,
    },
    // multFloat: {
    //     dataType: "float",
    // type:,
    // inputHandlesCount: 2,
    //oresultOffset:null
    // utputHandlesCount: 1,
    //     width: 0,
    //     height: 0,
    // },
    subInt: {
        dataType: "int",
        type: "subInt",
        inputHandlesCount: 2,
        resultOffset: null,
        outputHandlesCount: 1,
    },
    // subFloat: {
    //     dataType: "float",
    // type:,
    // inputHandlesCount: 2,
    //oresultOffset:null
    // utputHandlesCount: 1,
    //     width: 0,
    //     height: 0,
    // },
    // outputInt: {
    //     name: "",
    //     width: 0,
    //     height: 0,
    //     dataType: "int",
    // type:,
    // inputHandlesCount: 0,
    //oresultOffset:null
    // utputHandlesCount: 1,
    // },
    // outputBool: {
    //     name: "",
    //     width: 0,
    //     height: 0,
    //     dataType: "bool",
    // type:,
    // inputHandlesCount: 0,
    // resultOffset:null
    // outputHandlesCount: 1,
    // },
    // outputFloat: {
    //     name: "",
    //     width: 0,
    //     height: 0,
    //     dataType: "float",
    // type:,
    // inputHandlesCount: 0,
    // resultOffset:null
    // outputHandlesCount: 1,
    // },
    // muxBool: {
    //     dataType: "bool",
    // type:,
    // inputHandlesCount: 3,
    // resultOffset:null
    // outputHandlesCount: 1,
    //     width: 0,
    //     height: 0,
    // },
    // muxInt: {
    //     dataType: "int",
    // type:,
    // inputHandlesCount: 3,
    // resultOffset:null
    // outputHandlesCount: 1,
    //     width: 0,
    //     height: 0,
    // },
    equalsInt: {
        dataType: "int",
        type: "equalsInt",
        inputHandlesCount: 2,
        resultOffset: null,
        outputHandlesCount: 1,
    },
    // equalsFloat: {
    //     dataType: "float",
    // type:,
    // inputHandlesCount: 2,
    // resultOffset:null
    // outputHandlesCount: 1,
    //     width: 0,
    //     height: 0,
    // },
    lessInt: {
        dataType: "int",
        type: "lessInt",
        inputHandlesCount: 2,
        resultOffset: null,
        outputHandlesCount: 1,
    },
    // lessFloat: {
    //     dataType: "float",
    // type:,
    // inputHandlesCount: 2,
    // resultOffset:null
    // outputHandlesCount: 1,
    //     width: 0,
    //     height: 0,
    // },
    moreInt: {
        dataType: "int",
        type: "moreInt",
        inputHandlesCount: 2,
        resultOffset: null,
        outputHandlesCount: 1,
    },
    // moreFloat: {
    //     dataType: "float",
    // type:,
    // inputHandlesCount: 2,
    // resultOffset:null
    // outputHandlesCount: 1,
    //     width: 0,
    //     height: 0,
    // },
    timerInt: {
        dataType: "int",
        type: "timerInt",
        name: "t",
        inputHandlesCount: 0,
        resultOffset: null,
        outputHandlesCount: 1,
    },
    constInt: {
        dataType: "int",
        type: "constInt",
        name: "c",
        setpointOffset: null,
        inputHandlesCount: 0,
        outputHandlesCount: 1,
    },
    constBoolean: {
        dataType: "bool",
        type: "constBoolean",
        name: "c",

        inputHandlesCount: 0,
        resultOffset: null,
        outputHandlesCount: 1,
    },
    dtrigger: {
        dataType: "bool",
        type: "dtrigger",

        inputHandlesCount: 1,
        resultOffset: null,
        outputHandlesCount: 1,
    },
};
