import { TNodeConfigurations } from "./types";

export const nodeConfigurations: TNodeConfigurations = {
    discreteInput: {
        dataType: "int",
        type: "discreteInput",
        handlesCount: 0,
        name: "",
        width: 0,
        height: 0,
    },
    discreteOutput: {
        dataType: "int",
        type: "discreteInput",
        handlesCount: 0,
        name: "",
        width: 0,
        height: 0,
    },

    inputFloat: {
        dataType: "float",
        type: "inputFloat",
        handlesCount: 0,
        name: "",
        width: 0,
        height: 0,
    },
    inputInt: {
        dataType: "int",
        type: "inputInt",
        handlesCount: 0,
        name: "",
        width: 0,
        height: 0,
    },
    xor: {
        dataType: "bool",
        type: "xor",
        handlesCount: 2,
        width: 0,
        height: 0,
    },
    and: {
        dataType: "bool",
        type: "and",
        handlesCount: 3,
        width: 0,
        height: 0,
    },
    or: {
        dataType: "bool",
        type: "or",
        handlesCount: 3,
        width: 0,
        height: 0,
    },
    nand: {
        dataType: "bool",
        type: "nand",
        handlesCount: 3,
        width: 0,
        height: 0,
    },
    nor: {
        dataType: "bool",
        type: "nor",
        handlesCount: 3,
        width: 0,
        height: 0,
    },
    notOperation: {
        dataType: "bool",
        type: "notOperation",
        handlesCount: 1,
        width: 0,
        height: 0,
    },
    sumInt: {
        dataType: "int",
        type: "sumInt",
        handlesCount: 2,
        width: 0,
        height: 0,
    },
    // sumFloat: {
    //     dataType: "float",
    // type:,
    // handlesCount: 2,
    //     width: 0,
    //     height: 0,
    // },
    multInt: {
        dataType: "int",
        type: "multInt",
        handlesCount: 2,
        width: 0,
        height: 0,
    },
    // multFloat: {
    //     dataType: "float",
    // type:,
    // handlesCount: 2,
    //     width: 0,
    //     height: 0,
    // },
    subInt: {
        dataType: "int",
        type: "subInt",
        handlesCount: 2,
        width: 0,
        height: 0,
    },
    // subFloat: {
    //     dataType: "float",
    // type:,
    // handlesCount: 2,
    //     width: 0,
    //     height: 0,
    // },
    // outputInt: {
    //     name: "",
    //     width: 0,
    //     height: 0,
    //     dataType: "int",
    // type:,
    // handlesCount: 0,
    // },
    // outputBool: {
    //     name: "",
    //     width: 0,
    //     height: 0,
    //     dataType: "bool",
    // type:,
    // handlesCount: 0,
    // },
    // outputFloat: {
    //     name: "",
    //     width: 0,
    //     height: 0,
    //     dataType: "float",
    // type:,
    // handlesCount: 0,
    // },
    // muxBool: {
    //     dataType: "bool",
    // type:,
    // handlesCount: 3,
    //     width: 0,
    //     height: 0,
    // },
    // muxInt: {
    //     dataType: "int",
    // type:,
    // handlesCount: 3,
    //     width: 0,
    //     height: 0,
    // },
    equalsInt: {
        dataType: "bool",
        type: "equalsInt",
        handlesCount: 2,
        width: 0,
        height: 0,
    },
    // equalsFloat: {
    //     dataType: "float",
    // type:,
    // handlesCount: 2,
    //     width: 0,
    //     height: 0,
    // },
    lessInt: {
        dataType: "bool",
        type: "lessInt",
        handlesCount: 2,
        width: 0,
        height: 0,
    },
    // lessFloat: {
    //     dataType: "float",
    // type:,
    // handlesCount: 2,
    //     width: 0,
    //     height: 0,
    // },
    moreInt: {
        dataType: "bool",
        type: "moreInt",
        handlesCount: 2,
        width: 0,
        height: 0,
    },
    // moreFloat: {
    //     dataType: "float",
    // type:,
    // handlesCount: 2,
    //     width: 0,
    //     height: 0,
    // },
    timerInt: {
        dataType: "int",
        type: "timerInt",
        name: "t",
        width: 0,
        height: 0,
        handlesCount: 0,
    },
    сonstInt: {
        dataType: "int",
        type: "сonstInt",
        name: "c",
        width: 0,
        height: 0,
        handlesCount: 0,
    },
    constBoolean: {
        dataType: "bool",
        type: "constBoolean",
        name: "c",
        width: 0,
        height: 0,
        handlesCount: 0,
    },
    dtrigger: {
        dataType: "bool",
        type: "dtrigger",
        width: 0,
        height: 0,
        handlesCount: 1,
    },
};
