export const projectsData = [
  {
    id: 1,
    name: "name1",
    dimensions: "тест",
    indication: "тест",
    weight: 200,
    algoritms: "algoritms",
    keyСharacteristic: ["", "", ""],
    imgSrc: "",
  },
  {
    id: 2,
    name: "name2",
    dimensions: "тест",
    indication: "тест",
    weight: 200,
    algoritms: "algoritms",
    keyСharacteristic: ["", "", ""],
    imgSrc: "",
  },
  {
    id: 3,
    name: "name3",
    dimensions: "тест",
    indication: "тест",
    weight: 200,
    algoritms: "algoritms",
    keyСharacteristic: ["", "", ""],
    imgSrc: "",
  },
  {
    id: 4,
    name: "name4",
    dimensions: "тест",
    indication: "тест",
    weight: 200,
    algoritms: "algoritms",
    keyСharacteristic: ["", "", ""],
    imgSrc: "",
  },
];
